const exception = function(message) {
    return { 'error': message };
};

exports.error_exception = exception;